xmtp/xmtpd

.github/workflows/lint.yml, .github/workflows/test.yml, .vscode/settings.json, dev/lint-shellcheck
- Adds Github actions
- Adds shellcheck script
- Updates vscode config to use the correct lint tool
=> add github actions

README.md, pkg/migrations/00001_init-schema.down.sql, pkg/migrations/00001_init-schema.up.sql, pkg/server/server.go
Creates initial database schema, feedback welcome as this heavily influences implementation.
Because I modified an existing migration, you may need to run `dev/down` and `dev/up` before running tests again.
=> Create initial DB schema

.vscode/extensions.json, .vscode/settings.json, README.md, cmd/replication/main.go, dev/up, pkg/api/server.go, pkg/api/service.go, pkg/api/service_test.go, pkg/db/pgx.go, pkg/migrations/migrations.go, pkg/server/server.go, pkg/server/server_test.go, pkg/testing/store.go, pkg/utils/envelope.go, pkg/utils/sid.go
Initial implementation of the publish endpoint and unit test setup. Simply writes to the staged envelopes table and does nothing else.
Also fixed some issues around DB and connection lifetimes - the migration step now closes the connection it uses (but not the whole DB instance).
=> Initial publish implementation

dev/up
I needed this when first running `dev/up`
=> Also install the `buf` package

.github/workflows/build-xmtpd.yml, dev/docker/Dockerfile
Builds the xmtpd docker image and pushes it to GHCR.
Based on [libxmtp](https://github.com/xmtp/libxmtp/blob/533efcb221cfa334198a0d0b81131b0175c4f5f2/.github/workflows/deploy-validation-server.yml#L18-L42).
The notable difference is that it also builds the image (but does not push) on PRs. Useful for CI.
The resulting image example can already be seen [here](https://github.com/xmtp/xmtpd/actions/runs/10356333475?pr=108)
Fixes #104
=> Build xmtpd docker image and push to ghcr

.mockery.yaml, contracts/src/Nodes.sol, contracts/test/GroupMessage.t.sol, contracts/test/Nodes.sol, pkg/abis/nodes.go, pkg/registry/registry.go
- Rewrites Nodes contract using the ERC721 standard as a base
- Adds a bunch of tests for the new smart contract
- Removes a deprecated flag from our mockery config
1. It doesn't seem crazy to model this registry as a NFT, so we might as well use the standard.
2. We get all the OpenZeppelin audited smart contract libraries for free
3. It'll work with the entire rest of the crypto ecosystem (external indexers, other smart contracts, etc) automatically
1. **Smart Contract Changes**:
- Implemented ERC721 standard in the `Nodes` contract.
- Added new functions for node management using NFTs: `addNode`, `removeNode`, `updateHttpAddress`, `updateMtlsCert`, and `updateHealth`.
- Added events `NodeUpdated` and `NodeRemoved` for better tracking of node changes.
- Restricted node ownership …
=> Update node contract

pkg/indexer/blockchain/rpcLogStreamer.go
- Addresses PR feedback and has the indexer sleep for 1 second when no logs are received. 
- Start with a smaller sleep time and use exponential backoff
=> Sleep when no logs

README.md, dev/generate, pkg/db/queries.sql, pkg/db/queries/models.go, pkg/db/queries/queries.sql.go, pkg/migrations/00001_init-schema.up.sql, pkg/registrant/registrant.go, pkg/utils/sid.go, pkg/utils/sid_test.go
I've fixed a number of issues, would like to suggest some best practices going forward that I've implemented here:
1. **Reliable sequence ID's**. Whenever we add a table that uses a sequence for ordering, we should also add a Postgres stored function immediately below it that performs insertions by taking an advisory lock first. This ensures that inserts on the table are [processed serially](https://espadrine.github.io/blog/posts/two-postgresql-sequence-misconceptions.html#Order_violation).
2. **Idempotent inserts**. Whenever we add an insert query, we should add an `ON CONFLICT DO NOTHING` clause, and either return the inserted count via `:execrows` or the row itself via `:one`. This saves the caller from having to parse untyped errors in search of unique constraint violations, which are …
=> Add more queries, fix DB sequence ID's

pkg/api/publishWorker.go, pkg/api/service.go, pkg/api/service_test.go, pkg/db/queries.sql, pkg/db/queries/models.go, pkg/db/queries/queries.sql.go, pkg/migrations/00001_init-schema.up.sql, pkg/registrant/registrant.go
- Adds a publish worker that performs in-order insertion into the `gateway_envelopes` table
- Adds basic validation of the client envelope on publish
- Store the topic on the `staged_originated_envelopes` table - we extract this during the API call, so that the publish worker doesn't need to do any additional unmarshaling or validation.
Would particularly love feedback on the error handling in the worker, and if there's any test cases I should add to `service_test.go`.
=> Add publish worker

dev/docker/Dockerfile, pkg/config/options.go
Pre-PR we expose a different port than the docker image expects.
I picked `80` since it makes the most sense, but we can pick any other port if people have opinions.
=> Unify port

pkg/api/service_test.go, pkg/db/subscription_test.go, pkg/indexer/blockchain/rpcLogStreamer_test.go, pkg/indexer/indexer_test.go, pkg/indexer/storer/groupMessage_test.go, pkg/registrant/registrant_test.go, pkg/registry/contractRegistry_test.go, pkg/server/server_test.go, pkg/testutils/config.go, pkg/testutils/contracts.go, pkg/testutils/hex.go, pkg/testutils/log.go, pkg/testutils/random.go, pkg/testutils/store.go
- It was annoying having to alias the `testing` package everywhere it was used because the name conflicts with the standard `testing` package. This renames it
=> Rename testing to testutils

dev/docker/Dockerfile, dev/psql, pkg/config/options.go
1) Do not pass `--help` to the docker image. This forces the caller which only wishes to use ENV variables to pass an empty command. This makes it hard in Terraform.
2) add a psql convenience script to connect to the local PG instance
3) mark `signer-private-key` as `required`
=> Combined small improvements

.github/workflows/build-xmtpd.yml, dev/run
Automatically tag a docker image by it's git sha.
This is useful for pinning and debugging.
For example:
```
Docker tags
ghcr.io/xmtp/xmtpd:pr-134
ghcr.io/xmtp/xmtpd:sha-56e2af4
```
Drive-by allow passing args to `dev/run` such as `./dev/run --api.port=1000`
=> Tag by SHA

cmd/replication/main.go, pkg/api/server.go, pkg/server/server.go
- Updates the way we shut down the server to be a little simpler
- Adds a `gracefulShutdown` function on the API server that will reject new connections but not immediately kill existing ones, so that the server can finish short-lived requests
=> Clean up shutdown logic

.idea/vcs.xml, go.mod, pkg/api/server.go, pkg/config/options.go, pkg/server/server.go
https://github.com/grpc/grpc-go/blob/master/Documentation/server-reflection-tutorial.md
This enables stuff like:
```
$ grpcurl -plaintext localhost:1005 grpc.health.v1.Health.Check
{
"status": "SERVING"
}
```
And later more advanced endpoint querying.
I am not sure I would enable this in `prod`, but for `testnet` it's amazing.
=> Enable server reflection

pkg/api/publishWorker.go, pkg/api/service.go, pkg/api/subscribeWorker.go, pkg/api/subscribe_test.go, pkg/db/queries.sql, pkg/db/queries/queries.sql.go, pkg/db/subscription.go, pkg/db/types.go, pkg/testutils/api.go, pkg/testutils/envelopes.go
Introduces a basic initial version of client subscriptions. A worker maintains a global database subscription, and pushes updates to relevant client listeners.
There are many pieces coming in later PR's:
- Thread safety for adding and reading listeners
- Listener cleanup, esp when channels are full
- Subscribing from a vector clock cursor (which also gives a way to recover from backpressure)
- Logging and load/performance metrics
- Bidirectional streaming
#125
=> Non-thread-safe subscriptions

pkg/api/service.go, pkg/api/subscribeWorker.go, pkg/api/subscribe_test.go
This PR adds:
- Thread-safety for mutation of listener maps
- Safe cleanup flow for listener channels
As a general principle, we use Golang's `sync.map`. This is an optimistic concurrency pattern that restricts contention to a per-key level, and separates reads and writes via a read-only map and dirty map. So the dispatch loop is not affected - any mutations to the sync maps are performed outside of the dispatching goroutine.
I've also added a `RWMutex` to synchronize between adding and removing listeners. The main thing we are protecting against is that when removing a listener, we may want to delete the `listenerset` if it is empty - but we can't perform the emptiness check and the deletion step atomically without a mutex. I think this should be okay, because in the current server we …
=> Thread-safe subscriptions and listener cleanup

README.md, dev/up
TL;DR: Due to an incompatibility with go 1.23 and a dependency of abigen, devs must explicitly install go 1.22 (ex: using brew install go@1.22) and golangci-lint 1.56.
xmtpd requires abigen which uses memsize. memsize relies on access to `runtime.stopTheWorld` and `runtime.startTheWorld` [1] which was OK in go 1.22 and forbidden in go 1.23
[1] https://github.com/golang/go/issues/68167
=> Document go 1.22 and golangci-lint 1.56 requirements

pkg/api/server.go
Once graceful shutdown times out, it does not actually kill itself. Fix it.
=> Fix graceful shutdown

dev/docker/up
In some cases there is a race between the blockchain container and the process inserting new nodes.
Make sure the processes are all up in `detached` mode.
=> Wait for container processes

.github/workflows/build-xmtpd.yml, .idea/watcherTasks.xml, cmd/replication/main.go, dev/docker/Dockerfile, dev/docker/build, dev/run, pkg/config/options.go
This correctly injects the git sha into the image so that we can query it with `--version`.
More importantly, the version will now show up in the datalog logs.
=> Fix Versioning

dev/up
One needs to run `foundryup` and add the `bin` to the path. Given that every user might prefer a different manipulation of their PATH, it is hard to automate.
This tripped up @codabrink when trying things out
=> Fix up instructions

dev/generate, pkg/api/query_test.go, pkg/api/service.go, pkg/api/subscribe_test.go, pkg/db/queries.sql, pkg/db/queries/queries.sql.go, pkg/db/subscription_test.go, pkg/db/types.go, pkg/indexer/e2e_test.go, pkg/indexer/storer/groupMessage_test.go, pkg/indexer/storer/identityUpdate.go, pkg/indexer/storer/identityUpdate_test.go, pkg/migrations/00002_select-gateway-envelopes.down.sql, pkg/migrations/00002_select-gateway-envelopes.up.sql
Implements batch querying and unit tests, which will also be used in the next PR for catch-up of historical messages when streaming. Also got rid of our use of NullInt32 in queries, which simplifies the go code a little.
For now we let up to 10k topics be specified in these queries - we can do proper benchmarking and SQL analyzing later to see how we should adjust it.
Closes #218
=> Add support for batch query

pkg/sync/syncWorker.go, pkg/utils/grpc.go
Load TLS certs from host machine if possible.
Determine whether TLS should be used based on HTTPS scheme.
`passthrough` and `dns` are technically not required.
All tests still pass. A local node can now connect to `testnet`. Local nodes can peer.
=> Fix GRPC TLS

pkg/api/publish_test.go, pkg/api/query_test.go, pkg/api/service.go, pkg/api/subscribe_test.go, pkg/envelopes/client.go, pkg/envelopes/envelopes_test.go, pkg/envelopes/payer.go, pkg/server/server_test.go, pkg/testutils/envelopes/envelopes.go, pkg/testutils/proto.go
- Uses new `envelopes` structs to help validate publish requests
- Validates that the topic matches the payload (https://github.com/xmtp/xmtpd/issues/231)
Refactored envelope handling and improved validation in the API service.
- Moved envelope-related test utilities to a dedicated package `pkg/testutils/envelopes`.
- Enhanced `ClientEnvelope` struct with additional methods for topic handling and payload validation.
- Updated `Service.PublishEnvelopes` to use the new envelope validation logic.
- Improved error handling and messages in various API functions.
- Introduced `TopicMatchesPayload` method to ensure consistency between envelope topic and payload.
1. Run the existing test suite to ensure all tests pass after the refactoring.
2. Add new tests to cover the `TopicMatchesPayload` …
=> Validate published envelope topics

pkg/authn/signingMethod.go, pkg/constants/constants.go, pkg/envelopes/envelopes_test.go, pkg/envelopes/payer.go, pkg/utils/hash.go, pkg/utils/signature.go
- Adds method to recover the signer from payer envelopes (https://github.com/xmtp/xmtpd/issues/232)
- Refactors domain separation for jwt's and payer envelopes
Introduced domain separation for payer signatures, and added functionality to recover signer addresses from payer envelopes.
- Created a new `constants` package with domain separation labels for JWT and payer signatures.
- Updated the JWT signing method to use the new constant for domain separation.
- Implemented a `RecoverSigner` method for `PayerEnvelope` to extract the signer's address.
- Added utility functions for hashing and signing payer envelopes.
- Expanded test coverage for envelope signer recovery.
This change enhances security and consistency by introducing domain separation for signatures. It also adds the ability to …
=> Recover signer from payer envelopes

pkg/authn/tokenFactory.go, pkg/authn/verifier_test.go, pkg/constants/constants.go, pkg/interceptors/client/auth.go, pkg/interceptors/client/auth_test.go, pkg/registrant/registrant.go, pkg/sync/syncWorker.go
- Creates a client interceptor for attaching auth tokens to requests
- Actually attaches JWTs to requests coming from the sync service
Implemented node-to-node authentication using JWT tokens for secure communication between XMTP nodes.
- Added an `AuthInterceptor` for client-side gRPC calls to inject JWT tokens into request headers.
- Updated the `TokenFactory` to use `uint32` for node IDs instead of `int32`.
- Modified the `Registrant` to include a `TokenFactory`.
- Updated the `syncWorker` to use the new `AuthInterceptor` when connecting to other nodes.
- Added a new constant `NODE_AUTHORIZATION_HEADER_NAME` for the authentication header.
- Created mock implementations and tests for the new authentication system.
1. Run the existing test suite to ensure no regressions.
2. Check the new …
=> Add auth token to GRPC requests

pkg/api/message/publishWorker.go, pkg/api/message/publish_test.go, pkg/api/message/service.go, pkg/api/message/subscribeWorker.go, pkg/api/message/subscribe_test.go, pkg/api/server.go, pkg/interceptors/client/auth_test.go
- Small refactor to move the GRPC services into subfolders
=> Move message api into its own folder

pkg/api/payer/service.go, pkg/api/server.go
=> Scaffold payer service

pkg/api/payer/clientManager.go, pkg/api/payer/clientManager_test.go, pkg/api/payer/service.go, pkg/api/server.go, pkg/registry/node.go, pkg/server/server.go, pkg/sync/syncWorker.go, pkg/testutils/api/api.go
- Introduces a new `ClientManager` for managing gRPC client connections
- Implements a `RegistrationFunc` callback for registering gRPC services
- Refactors `NewAPIServer` to use the `RegistrationFunc` instead of direct service creation
- Adds `BuildClient` method to `Node` struct for creating gRPC client connections
- Updates test utilities to use the new service registration approach
Two reasons:
1. I wanted to get the dependencies and logic of building the individual services out of the `api` module and make that solely focused on creating an API server
2. Some server's will have just a payer API, some will have a message and payer API. I wanted to move that decision making up a layer in the stack.
This PR introduces a `ClientManager` to handle gRPC client connections efficiently. It …
=> Add node connection manager

pkg/indexer/e2e_test.go, pkg/indexer/storer/groupMessage.go, pkg/indexer/storer/groupMessage_test.go, pkg/indexer/storer/identityUpdate_test.go, pkg/testutils/contracts.go, pkg/testutils/envelopes/envelopes.go, pkg/topic/topic_test.go
- Updates the group messages blockchain reader to expect `ClientEnvelope` payloads instead of raw messages.
=> Update group messages to expect ClientEnvelopes

cmd/replication/main.go, pkg/api/server.go, pkg/server/server.go, pkg/server/server_test.go, pkg/testutils/api/api.go
The unit tests currently spin up instances of the server that accept all incoming connections, which causes a security dialog on Macs. Instead, for unit tests we only want to listen for incoming connections coming from localhost.
=> Only listen on localhost for unit tests

.github/workflows/build-xmtpd.yml, cmd/cli/main.go, dev/cli, dev/docker/Dockerfile-cli
Partners might have to run the CLI to export the public key (or generate it in the first place) and provide it to Ephemera for use in the `testnet`.
It is not too convenient to download the repo, install go, just to run the CLI.
Build a docker image instead.
We will eventually need releases here in GH for easy download, and `homebrew` as well.
The important question is. How should this binary be called?
This should help @jhaaaa with docs.
=> Build CLI Docker Image

dev/cli
You have to run the CLI from the repo root such as `./dev/cli`, but it should be runnable from anywhere.
This fixes it.
See:
```
martinkysel@Mac xmtpd (mkysel/fix-cli) $ ./dev/cli 
Please specify one command of: generate-key, get-all-nodes, get-pub-key, mark-healthy, mark-unhealthy, register-node or update-address
2024/12/04 15:52:05 Could not parse options: Could not parse options: Please specify one command of: generate-key, get-all-nodes, get-pub-key, mark-healthy, mark-unhealthy, register-node or update-address
exit status 1
martinkysel@Mac xmtpd (mkysel/fix-cli) $ cd dev/
martinkysel@Mac dev (mkysel/fix-cli) $ ./cli 
Please specify one command of: generate-key, get-all-nodes, get-pub-key, mark-healthy, mark-unhealthy, register-node or update-address
2024/12/04 15:52:12 Could not …
```
=> Run CLI from any directory

.github/workflows/lint-go.yml, .github/workflows/lint-spellcheck.yml, .github/workflows/lint.yml, .github/workflows/solidity.yml, .github/workflows/test.yml
This is based on how we do things in [libxmtp](https://github.com/xmtp/libxmtp/blob/main/.github/workflows/test-http-api.yml)
There are two major changes:
- always run all tests in `main`
- be more deliberate about ignoring node tests in some scenarios
=> Rework how we ignore changes in CI

dev/up
Following the [official docs](https://golangci-lint.run/welcome/install/), it seems that `homebrew` is the best way to install the linter.
We do not pin the version in the CI anyway
=> Use homebrew for linter

.github/workflows/release-from-tag.yml
The GitHub Actions workflow in [release-from-tag.yml](https://github.com/xmtp/xmtpd/pull/791/files#diff-cee4eadd46d2585fd337f530116877504920be9ec452bdbfb915b95857438208) is updated to build and push a new `xmtpd-prune` Docker image using `Dockerfile-prune`. The workflow matrix now includes three images: `xmtpd`, `xmtpd-cli`, and `xmtpd-prune`.
Start with the workflow configuration in [release-from-tag.yml](https://github.com/xmtp/xmtpd/pull/791/files#diff-cee4eadd46d2585fd337f530116877504920be9ec452bdbfb915b95857438208) which contains the matrix configuration and build conditions for the Docker images.
----
_[Macroscope](https://app.macroscope.com) summarized 988813c._
=> Add prune release to rel from tag

dev/docker/docker-compose-register.yml, dev/docker/docker-compose.yml, dev/docker/down, dev/docker/up, dev/down, dev/up
* Updates Docker Compose configuration in [docker-compose-register.yml](https://github.com/xmtp/xmtpd/pull/822/files#diff-a1e7ac7430bed8c9bdd26624200229b35a1eeb5363eb27128ae4eb71bad7f83c) to build `xmtpd-cli` image locally instead of using pre-built image
* Adds profile support in [docker-compose.yml](https://github.com/xmtp/xmtpd/pull/822/files#diff-6a25daaa729d7279e0cda8eb92399f1a82d4a91f961e1955bb5745e9c99f3c6e) to conditionally activate database services based on `single` or `dual` profiles
* Enhances [up](https://github.com/xmtp/xmtpd/pull/822/files#diff-c4a1f6ed02b85cec2e690a289e7810fd5639c9abf2f205bba12519957bb06f99) and [down](https://github.com/xmtp/xmtpd/pull/822/files#diff-7d10e63db3d97298d86fb22d36c4c0fb11bf8aa78cdc8566d33d1bebbb81b51b) scripts with robust profile validation …
=> Rework compose up/down

pkg/config/options.go, pkg/config/validation.go, pkg/indexer/app_chain/app_chain.go, pkg/indexer/common/block_tracker.go, pkg/indexer/common/block_tracker_test.go, pkg/indexer/settlement_chain/settlement_chain.go
The configuration system now uses a single `DeploymentBlock` field instead of multiple contract-specific start block fields for blockchain indexing initialization. Key changes include:
• Removal of `GroupMessageBroadcasterStartBlock`, `IdentityUpdateBroadcasterStartBlock`, `PayerRegistryStartBlock`, and `PayerReportManagerStartBlock` fields from configuration structs in [pkg/config/options.go](https://github.com/xmtp/xmtpd/pull/873/files#diff-6731fb6f709392ce3e37d3b0c42074cddbce566dad2bab86af24ba7585eeb57c)
• Addition of `DeploymentBlock` fields to both `AppChainOptions` and `SettlementChainOptions` structs with default value of 0
• Updates to validation logic in [pkg/config/validation.go](https://github.com/xmtp/xmtpd/pull/873/files#diff-3e0b3707cc5d712d06d1eeb6a67c10b45a7ba0b27e972924d71 …
=> Honor start at deployment blocks

pkg/api/message/publishWorker.go, pkg/sync/originatorStream.go
- Adds originator ID and sequence ID context to debug log messages when envelopes are already inserted in [publishWorker.go](https://github.com/xmtp/xmtpd/pull/882/files#diff-cd2a58705d7eacdaf32fc6b4148beb71638e391186b9682bd0c678a91362ce7b)
- Adds envelope and lastEnvelope details to error logs for out-of-order envelopes and changes log level from Info to Debug for duplicate envelope messages while adding originator ID and sequence ID context in [originatorStream.go](https://github.com/xmtp/xmtpd/pull/882/files#diff-ef2c8eedfaea0d04082c5ce6c5835dc2a0886632e5eb547ca5c79e01b12cd6a2)
Start with the logging changes in [publishWorker.go](https://github.com/xmtp/xmtpd/pull/882/files#diff-cd2a58705d7eacdaf32fc6b4148beb71638e391186b9682bd0c678a91362ce7b) where the duplicate envelope detection …
=> Add more debug info to duplicate inserts

.github/workflows/test.yml
This should fix #883. Edit: it actually makes no sense to report CI success on branches. Only do this for main. And only if this is on a non-fork.
=> Skip DD test report upload for fork PRs

pkg/indexer/common/log_handler.go, pkg/registry/notifier_test.go
=> chore: fix typos

.github/workflows/lint-shellcheck.yml, dev/cmd/register-local-node-1, dev/cmd/register-local-node-2, dev/docker/down, dev/docker/up
Adds double quotes around variable references in shell scripts to prevent word splitting and globbing issues, and renames the GitHub workflow from spellcheck to shellcheck. The changes affect multiple shell scripts:
- Renames [.github/workflows/lint-spellcheck.yml](https://github.com/xmtp/xmtpd/pull/890/files#diff-cbd3901c3e303473edf0ca1d9c26f0261f224b92a8ea719558a9c5d5f73f4d2a) to `lint-shellcheck.yml` and updates workflow name and job name
- Adds quotes around variable references in [dev/cmd/register-local-node-1](https://github.com/xmtp/xmtpd/pull/890/files#diff-bb71ba35eb76b858e97a2478cdb558d8107d1019fd90a42dad3dfe703c280bc2) for `NODE_ADDRESS`, `PRIVATE_KEY`, `XMTPD_SIGNER_PUBLIC_KEY`, and `NODE_ID` variables
- Adds quotes around variable references in …
=> Make shellcheck happy

pkg/indexer/rpc_streamer/rpc_log_streamer.go
The RPC log streamer now emits metrics during the subscription phase to track indexing progress. When transitioning from backfill to subscription mode, the code sets the current block lag to 0 using `metrics.EmitIndexerCurrentBlockLag`. For each log received from the subscription channel, three metrics are emitted: current block number via `metrics.EmitIndexerCurrentBlock`, log count increment via `metrics.EmitIndexerNumLogsFound`, and maximum block processed via `metrics.EmitIndexerMaxBlock`. All metrics are associated with the indexed address using `cfg.Address.Hex()` as the identifier. The changes are contained within [pkg/indexer/rpc_streamer/rpc_log_streamer.go](https://github.com/xmtp/xmtpd/pull/889/files#diff-10e2ad066301e371b4055118a8d04f20723857f2c6158609bf3c33b5237e5b4d).
Start …
=> Update metrics on subscription

dev/docker/up, go.mod, pkg/config/validation.go
The `validateWebsocketURL` function in [pkg/config/validation.go](https://github.com/xmtp/xmtpd/pull/887/files#diff-3e0b3707cc5d712d06d1eeb6a67c10b45a7ba0b27e972924d71df3c8e539f23b) now accepts a `chainID` parameter and establishes an actual connection to Ethereum nodes to verify the chain ID matches the expected value. The function performs URL parsing validation, checks for proper websocket schemes (`ws` or `wss`), connects using `ethclient`, and confirms the node's chain ID. Additionally, the Docker Compose script receives proper quoting for profile variables, and the `gorilla/websocket` dependency changes from direct to indirect status in [go.mod](https://github.com/xmtp/xmtpd/pull/887/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6).
Start with the …
=> Validate provided chains with chainID

cmd/replication/main.go, pkg/api/server.go, pkg/payerreport/workers/integration_test.go, pkg/server/server.go, pkg/server/server_test.go, pkg/testutils/api/api.go, pkg/testutils/network/port.go, pkg/testutils/server/server.go
Some of our tests fail because there is a timing gap between our test discovering a socket, and the test actually using the socket. This refactor discovers a socket and keeps the listener open until it is time to properly close it.
=> Close timing gap in socket discovery

pkg/payerreport/workers/integration_test.go
Fails frequently locally. Almost all the time in CI. Re-running test is tedious. Disabling until resolved (https://github.com/xmtp/xmtpd/issues/913)
=> Skip attestation test until a fix is found

pkg/sync/originatorStream.go
The code adds error handling for closed channel detection in the `originatorStream.listen` method within [pkg/sync/originatorStream.go](https://github.com/xmtp/xmtpd/pull/920/files#diff-ef2c8eedfaea0d04082c5ce6c5835dc2a0886632e5eb547ca5c79e01b12cd6a2). The modification introduces a second return value check when receiving from the `writeQueue` channel to detect if the channel is closed, and logs an error message before terminating the goroutine when closure is detected.
Start with the `originatorStream.listen` method in [pkg/sync/originatorStream.go](https://github.com/xmtp/xmtpd/pull/920/files#diff-ef2c8eedfaea0d04082c5ce6c5835dc2a0886632e5eb547ca5c79e01b12cd6a2).
----
_[Macroscope](https://app.macroscope.com) summarized e7028b9._
=> Check for closed channel

pkg/api/message/publishWorker.go, pkg/api/message/subscribeWorker.go, pkg/api/payer/nodeCursorTracker.go, pkg/sync/originatorStream.go, pkg/sync/syncWorker.go
The changes add channel closure detection across multiple components to handle closed channel scenarios gracefully:
- Modified `publishWorker.start()` method in [publishWorker.go](https://github.com/xmtp/xmtpd/pull/921/files#diff-cd2a58705d7eacdaf32fc6b4148beb71638e391186b9682bd0c678a91362ce7b) to check if `p.listener` channel is closed and log error before returning
- Modified `subscribeWorker.start()` method in [subscribeWorker.go](https://github.com/xmtp/xmtpd/pull/921/files#diff-a73ab8897a790989a2033ac2677ef15a461f5f7428d91e5ae576461f20919c83) to check if `s.dbSubscription` channel is closed and log error before returning  
- Modified `BlockUntilDesiredCursorReached()` method in [nodeCursorTracker.go](https://github.com/xmtp/xmtpd/pull/921/files#diff-53bc52b24f8bd6ebdbf96bf10c2fe152f92 …
=> Check closed channels

pkg/registry/contractRegistry_test.go, pkg/registry/notifier_test.go
- Removes the `TestStopOnContextCancel` test function entirely from [contractRegistry_test.go](https://github.com/xmtp/xmtpd/pull/938/files#diff-21066b83dafe5399d2b8dd62d65c7fdb8d1e6cefd498c3ff8a0d136d6c44f301)
- Modifies `TestContractRegistryChangedNodes` in [contractRegistry_test.go](https://github.com/xmtp/xmtpd/pull/938/files#diff-21066b83dafe5399d2b8dd62d65c7fdb8d1e6cefd498c3ff8a0d136d6c44f301) to use a validator function with `CountChannel` instead of a separate goroutine for processing subscription channels
- Updates the `CountChannel` function in [notifier_test.go](https://github.com/xmtp/xmtpd/pull/938/files#diff-1596fac0dfa2840fbb298785072d7b4b522ab34b8d319b6cccf6db83d69e0d63) to accept optional validator functions that validate each value received from the channel before …
=> Fix flaky registry tests

go.mod, pkg/api/metadata/service.go, pkg/mocks/metadata_api/mock_MetadataApiClient.go, pkg/proto/openapi/xmtpv4/metadata_api/metadata_api.swagger.json, pkg/proto/xmtpv4/metadata_api/metadata_api.pb.go, pkg/proto/xmtpv4/metadata_api/metadata_api.pb.gw.go, pkg/proto/xmtpv4/metadata_api/metadata_api_grpc.pb.go, pkg/server/server.go, pkg/testutils/api/api.go
The metadata API service now includes a `GetVersion` RPC method that returns the server's version as a string. The changes include:
- Add version field to `Service` struct in [pkg/api/metadata/service.go](https://github.com/xmtp/xmtpd/pull/957/files#diff-eac101b9b3412e0c38f70b290ed9a62394b8414802b777b472b3ca4ae017f935) and update constructor to accept version parameter
- Generate protobuf definitions and gRPC service code for `GetVersionRequest` and `GetVersionResponse` message types
- Update server initialization in [pkg/server/server.go](https://github.com/xmtp/xmtpd/pull/957/files#diff-104a11712684e520f0affa95e6a053faeb713306a10f69ee99b9729cc9dd1996) to pass `cfg.ServerVersion` to metadata service constructor
- Add mock implementations for testing the new `GetVersion` method
- Generate …
=> GetVersion metadata endpoint

dev/gen/abi
The `package` variable initialization in the `gen_go_bindings()` function is modified to declare the variable separately before assigning its value, rather than initializing it inline within the echo command in [dev/gen/abi](https://github.com/xmtp/xmtpd/pull/967/files#diff-07c185e365fc47359ea73e8726651811d883fd180b184e58d6309cf4a5f0d47c).
Start with the `gen_go_bindings()` function in [dev/gen/abi](https://github.com/xmtp/xmtpd/pull/967/files#diff-07c185e365fc47359ea73e8726651811d883fd180b184e58d6309cf4a5f0d47c).
----
_[Macroscope](https://app.macroscope.com) summarized f6b5d82._
=> Fix shellcheck error

pkg/config/options.go, pkg/indexer/rpc_streamer/rpc_log_streamer.go
- Restructures the `RPCLogStreamer.watchContract` method in [rpc_log_streamer.go](https://github.com/xmtp/xmtpd/pull/947/files#diff-10e2ad066301e371b4055118a8d04f20723857f2c6158609bf3c33b5237e5b4d) to handle subscription errors within the main loop and restart backfill process when errors occur
- Reduces the default `MaxChainDisconnectTime` in `AppChainOptions` struct from 300s to 60s in [options.go](https://github.com/xmtp/xmtpd/pull/947/files#diff-6731fb6f709392ce3e37d3b0c42074cddbce566dad2bab86af24ba7585eeb57c)
- Extracts subscription building logic into `buildSubscriptionWithBackoff` method and changes channel buffer size from hardcoded 100 to dynamic sizing based on expected logs per block
Start with the `watchContract` method in …
=> Backfill page on sub error

.github/workflows/build-xmtpd.yml
The GitHub workflow for building xmtpd images changes from using job outputs to artifacts for passing image digests between jobs. The workflow now saves digests for xmtpd, xmtpd-cli, and xmtpd-prune images as individual artifacts, downloads them in the deploy job, validates all three digests, and deploys both xmtpd server and xmtpd-prune images to the testnet environment in [.github/workflows/build-xmtpd.yml](https://github.com/xmtp/xmtpd/pull/972/files#diff-95afafe5dd4596d8cf6cb230db5ceef06301977a83094317aa0f85dcbd6a77d9).
Start with the modified `push_to_registry` job in [.github/workflows/build-xmtpd.yml](https://github.com/xmtp/xmtpd/pull/972/files#diff-95afafe5dd4596d8cf6cb230db5ceef06301977a83094317aa0f85dcbd6a77d9) to understand how image digests are now saved as artifacts instead …
=> Deploy multiple images in one go

pkg/indexer/rpc_streamer/rpc_log_streamer.go
The error handling in the `RPCLogStreamer.watchContract` method in [rpc_log_streamer.go](https://github.com/xmtp/xmtpd/pull/971/files#diff-10e2ad066301e371b4055118a8d04f20723857f2c6158609bf3c33b5237e5b4d) is modified to call `logger.Fatal()` instead of logging an error and calling `r.Stop()` when subscription rebuilding fails after the maximum disconnect time. This change occurs in two locations within the method and causes the application to terminate rather than attempt graceful shutdown when persistent connection failures occur.
Start with the `RPCLogStreamer.watchContract` method in [rpc_log_streamer.go](https://github.com/xmtp/xmtpd/pull/971/files#diff-10e2ad066301e371b4055118a8d04f20723857f2c6158609bf3c33b5237e5b4d) where the error handling behavior has been modified.
---- …
=> Guarantee data integrity after sub fails completely

pkg/integration/docker_utils_test.go
There is a [new function](https://pkg.go.dev/maps@go1.21.1#Copy) added in the go1.21 standard library, which can make the code more concise and easy to read.
=> refactor: use maps.Copy for cleaner map handling

pkg/indexer/rpc_streamer/rpc_log_streamer.go
The `buildSubscriptionWithBackoff` method in the `RPCLogStreamer` struct now explicitly returns `nil, err` when subscription rebuilding fails, replacing the previous implicit return that only returned the error. This change affects error handling in [pkg/indexer/rpc_streamer/rpc_log_streamer.go](https://github.com/xmtp/xmtpd/pull/989/files#diff-10e2ad066301e371b4055118a8d04f20723857f2c6158609bf3c33b5237e5b4d).
Start with the `buildSubscriptionWithBackoff` method in the `RPCLogStreamer` struct in [pkg/indexer/rpc_streamer/rpc_log_streamer.go](https://github.com/xmtp/xmtpd/pull/989/files#diff-10e2ad066301e371b4055118a8d04f20723857f2c6158609bf3c33b5237e5b4d).
----
_[Macroscope](https://app.macroscope.com) summarized 82f9c78._
=> Fix missing return

pkg/api/message/publish_test.go, pkg/api/message/service.go
The `Service.validateClientInfo` method in [service.go](https://github.com/xmtp/xmtpd/pull/1008/files#diff-1f687c3f8e69fec5867ded411d50bda02bef3661181fa7422b9dc66b7b57f3c2) now validates that messages cannot depend on node IDs ≥ 100, which represent non-commits, returning an error message "A message can not depend on a non-commit" when such dependencies are detected. A new test `TestPublishEnvelolopeDependsOnOriginator` has been added to [publish_test.go](https://github.com/xmtp/xmtpd/pull/1008/files#diff-b6d92459b9ec3f2503f1ccb187101664984e631b23275bd4a716b694de10408c) to verify this validation behavior, and an existing test has been updated to use node ID 97 instead of 1600.
Start with the `validateClientInfo` method in the `Service` struct in …
=> Prevent dependsOn for non-commits:

pkg/config/pruneOptions.go, pkg/prune/prune.go, pkg/prune/prune_test.go, pkg/testutils/log.go
- Adds `CountDeletable` boolean field to `config.PruneConfig` struct with CLI flag and environment variable support in [pkg/config/pruneOptions.go](https://github.com/xmtp/xmtpd/pull/1041/files#diff-fd23a98cbc9c92d896f65d69d65f90028001af86148579c59753f6715cd85e0c)
- Modifies `prune.Executor.Run` method to conditionally count deletable envelopes based on `CountDeletable` configuration and changes loop termination to stop when batch deletes fewer rows than `BatchSize` in [pkg/prune/prune.go](https://github.com/xmtp/xmtpd/pull/1041/files#diff-1a9bef57c3cc14ab5b07561eb0aece529ef508cc606a179483dace998beb9eff)
- Introduces `CapturingWriteSyncer` and `CapturingLogger` test utilities for in-memory log capture in [pkg/testutils/log.go](https://github.com/xmtp/xmtpd/pull/1041/files#diff-a027d16b7af0 …
=> Take the good improvements from node-go pruner

doc/metrics_catalog.md, pkg/metrics/metrics.go, pkg/metrics/migrator.go, pkg/migrator/migrator.go, pkg/migrator/reader.go, pkg/migrator/reader_test.go, pkg/migrator/transformer_test.go, pkg/migrator/types.go, pkg/migrator/writer.go
The migrator system now collects extensive metrics across the reader, transformer, and writer stages while implementing flow control through a semaphore-based inflight tracking system. The changes include:
- Addition of 15 new migrator-specific metrics in [pkg/metrics/migrator.go](https://github.com/xmtp/xmtpd/pull/1042/files#diff-94129ac032a24ee9c3f1a8c70772094f4d1e3d5979baeb72a86b511833303bcb) covering latency histograms, error counters, and sequence ID gauges
- Modification of `migrator.Migrator.migrationWorker` method in [pkg/metrics/migrator.go](https://github.com/xmtp/xmtpd/pull/1042/files#diff-ccb0d31b1e7491838a2e4c7f2f6523eed971d6f18d4c04f006e14e2767671693) to implement semaphore-based flow control with batchSize*4 maximum inflight records and comprehensive metrics emission
- …
=> Migrator writer is the source of truth

pkg/db/pgx.go
Closes https://github.com/xmtp/xmtpd/issues/466
=> Create db if not exists

pkg/config/migration.go, pkg/migrator/builder.go, pkg/migrator/migrator.go, pkg/migrator/migrator_test.go, pkg/server/server.go
This refactor removes contracts from migration server config and makes the migrator require contract options and the payer private key explicitly.
- Add `contracts` to `DBMigratorConfig`, introduce `migrator.WithContractsOptions`, and make `migrator.NewMigrationService` return error "contracts are required" when missing in [migrator.go](https://github.com/xmtp/xmtpd/pull/1087/files#diff-ccb0d31b1e7491838a2e4c7f2f6523eed971d6f18d4c04f006e14e2767671693)
- Change `migrator.setupBlockchainPublisher` to accept `payerPrivateKey string` and `*config.ContractsOptions`; update internal references and pass `*cfg` to `NewBlockchainPublisher` in [builder.go](https://github.com/xmtp/xmtpd/pull/1087/files#diff-46e4864b80a90cb84cdeb5bbfd4e38c43e8e721f6d561a0c561e872602970746)
- Remove `Contracts` from …
=> Pass contract options correctly

cmd/cli/main.go, pkg/blockchain/appchainAdmin.go, pkg/blockchain/appchainAdmin_test.go, pkg/blockchain/parameterAdmin.go, pkg/blockchain/settlementChainAdmin.go, pkg/blockchain/settlementchainAdmin_test.go, pkg/config/chainConfig.go, pkg/config/cliOptions.go, pkg/config/options.go, pkg/config/validation.go, pkg/testutils/config.go
- Expand CLI pause targets in [main.go](https://github.com/xmtp/xmtpd/pull/1090/files#diff-ed4d81d29a7267f93fd77e17993fd3491b9ef6ded18490b4514d10ed1d803bc2) by wiring `setPause`/`getPause` to `blockchain.AppChainAdmin` and a new `blockchain.SettlementChainAdmin`, with `setupSettlementChainAdmin` handling settlement-chain admin construction.
- Add `settlementChainAdmin` in [settlementChainAdmin.go](https://github.com/xmtp/xmtpd/pull/1090/files#diff-bddef5bfa08c3db7ad8e7feb3170713a75951cb3f006074727c832ecadcc63ec) to bind to SettlementChainGateway, PayerRegistry, and DistributionManager and implement get/set pause with on-chain `UpdatePauseStatus` transactions and event parsing.
- Extend `appChainAdmin` in [appchainAdmin.go](https://github.com/xmtp/xmtpd/pull/1090/files#diff-0e088f77670d3c11 …
=> More pause CLI commands

pkg/api/payer/publish_test.go, pkg/migrator/transformer.go, pkg/registrant/registrant.go
Previously expiry times were computed using `time.Now().AddDate(...)`, which
advances calendar days in local time. This caused expiry drift of ±1h when
crossing DST boundaries (e.g. Nov 2, 2025 in America/New_York), leading to
test failures and inconsistent retention windows.
We now calculate expiry as:
time.Now().UTC().Add(time.Hour * 24 * retentionDays)
This normalizes to UTC and ensures each "day" of retention is treated as an
exact 24-hour period, independent of daylight saving time changes or local
timezone shifts.
Tests updated accordingly to use the same UTC 24h-day semantics.
=> Normalize expiry calculation to UTC with fixed 24h days

cmd/xmtpd-cli/commands/admin_setup.go, cmd/xmtpd-cli/commands/appchain.go, cmd/xmtpd-cli/commands/key_management.go, cmd/xmtpd-cli/commands/node_registry.go, cmd/xmtpd-cli/commands/rate_registry.go, cmd/xmtpd-cli/commands/root.go, cmd/xmtpd-cli/commands/settlement.go
_Macroscope is automatically generating a new summary of this pull request including the latest commits..._
<picture>
<source media="(prefers-color-scheme: dark)" srcset="https://prasso.ai/static/prassoai-pr-loader-small-dark-no-text.gif">
</picture>
Fixes https://github.com/xmtp/xmtpd/issues/1114
=> Silence CLI usage print and unify error handling

pkg/config/validation.go
This change updates `config.ContractOptionsFromEnv` to accept configuration paths as local filesystem paths or URLs with `http`, `https`, or `file` schemes, applies a 10s HTTP client timeout, enforces 2xx responses, and limits reads to 10 KiB with contextual error wrapping. It also adds `net/http` to imports and wraps JSON unmarshal errors with context.
- Add HTTP fetching with 10s timeout and 2xx status requirement in `config.ContractOptionsFromEnv` in [validation.go](https://github.com/xmtp/xmtpd/pull/1131/files#diff-3e0b3707cc5d712d06d1eeb6a67c10b45a7ba0b27e972924d71df3c8e539f23b)
- Support `file://` URLs with path normalization and 10 KiB read limit in `config.ContractOptionsFromEnv` in [validation.go](https://github.com/xmtp/xmtpd/pull/1131/files#diff-3e0b3707cc5d712d06d1eeb6a67c10b45 …
=> Allow using HTTP config paths in the CLI

.github/workflows/release-goreleaser.yaml, .gitignore, .goreleaser.yaml
- Add a GitHub Actions workflow in [release-goreleaser.yaml](https://github.com/xmtp/xmtpd/pull/1133/files#diff-61560a689e7e64a8b34e16a7d5a14d63a1453251f166fb51ba0112c6a52205c4) that runs on tag pushes matching `v*`, pushes to `main`, pull requests, and manual dispatch, performs snapshot builds for non-tag events, publishes releases on tag pushes, and uploads `dist/**` artifacts.
- Introduce GoReleaser v2 config in [.goreleaser.yaml](https://github.com/xmtp/xmtpd/pull/1133/files#diff-7326b55c062b0f46fe9e39aace0a25f4515cf206040fb91a6fd2cae839f5e826) to build `xmtpd-cli` for linux/darwin on `amd64`/`arm64` with CGO disabled, embed version metadata via `ldflags`, package archives as `.zip` and `.tar.gz` with shell completions and LICENSE, generate checksums, and update the Homebrew cask in …
=> Create goreleaser process for building CLI and brew pushing

.github/workflows/build-xmtpd.yml
The GitHub Actions workflow updates the Terraform variable payload to include a third variable, `xmtpd_gateway_docker_image`, whose value is set from `steps.digests.outputs.gateway_image`. This change occurs in [build-xmtpd.yml](https://github.com/xmtp/xmtpd/pull/1157/files#diff-95afafe5dd4596d8cf6cb230db5ceef06301977a83094317aa0f85dcbd6a77d9) within the step that assembles and passes variables to Terraform Cloud.
Start with the workflow step that constructs Terraform variable lists in [build-xmtpd.yml](https://github.com/xmtp/xmtpd/pull/1157/files#diff-95afafe5dd4596d8cf6cb230db5ceef06301977a83094317aa0f85dcbd6a77d9), focusing on where `xmtpd_gateway_docker_image` is added and populated from `steps.digests.outputs.gateway_image`.
----
_[Macroscope](https://app.macroscope.com) summarized …
=> Update the Gateway image in staging

pkg/db/queries/envelopes.sql.go, pkg/db/sqlc/envelopes.sql, pkg/migrations/00016_vector_clock.down.sql, pkg/migrations/00016_vector_clock.up.sql, pkg/sync/originator_stream.go, pkg/sync/originator_stream_test.go, pkg/sync/sync_worker.go
This updates the vector clock query and stream initialization to use gateway timestamps instead of raw envelopes. - Replace `SelectVectorClock` SQL with a lateral join that returns `originator_node_id`, latest `originator_sequence_id`, and `gateway_time`, and regenerate query code to scan into `GatewayTime time.Time` in [envelopes.sql.go](https://github.com/xmtp/xmtpd/pull/1158/files#diff-3f51de4a0ba4deee29a5f71e1e2b1064e76742199ebc7af27f72735da3a76c2e) and update the SQL in [envelopes.sql](https://github.com/xmtp/xmtpd/pull/1158/files#diff-0db76750c39b995e412cfbdd8439a43304fa606c9a069d2573849894a125817e). - Create indexes `idx_gateway_envelopes_vector_clock` and `idx_gateway_envelopes_originator_node_id` in [00016_vector_clock.up.sql](https://github.com/xmtp/xmtpd/pull/1158/files#diff-565 …
=> Enhance vector clock performance

pkg/migrations/00016_vector_clock.up.sql
This change inserts a session-level directive before the covering index creation in the migration. It adds `SET statement_timeout = 0;` and an explanatory comment in [00016_vector_clock.up.sql](https://github.com/xmtp/xmtpd/pull/1163/files#diff-5655ad56d8b16a69f33177677f388c5a06449a686b8d9dfa36bfaa6e77d1cc4a).
Start with the session configuration at the top of [00016_vector_clock.up.sql](https://github.com/xmtp/xmtpd/pull/1163/files#diff-5655ad56d8b16a69f33177677f388c5a06449a686b8d9dfa36bfaa6e77d1cc4a) to review the `SET statement_timeout = 0;` addition.
----
_[Macroscope](https://app.macroscope.com) summarized 50e4991._
=> No timeout on migration 16

.github/workflows/lint-go.yml, dev/gen/env, dev/gen/metrics-catalog, dev/generate-env, doc/metrics_catalog.md, pkg/api/payer/service.go, pkg/api/payer/service_test.go, pkg/metrics/metrics.go, pkg/metrics/payer.go, pkg/proto/openapi/xmtpv4/payer_api/payer_api.swagger.json, pkg/proto/xmtpv4/payer_api/payer_api.pb.go, pkg/proto/xmtpv4/payer_api/payer_api.pb.gw.go, pkg/proto/xmtpv4/payer_api/payer_api_grpc.pb.go, pkg/registry/node_registry_contract.go
- Replace the reader-node API with a nodes-list API by updating `payer.Service.GetNodes` to return a flat list of node `HTTPAddress` values and emit `xmtp_payer_get_nodes_available_nodes` in [service.go](https://github.com/xmtp/xmtpd/pull/1169/files#diff-68452fc27f6bc31d33c1a89c833c0f4d3f76632124587b98e44b5e241629f280).
- Regenerate protobuf and gateway artifacts to rename request/response types to `GetNodes*` and change the HTTP route to `/mls/v2/payer/get-nodes` in [payer_api.pb.go](https://github.com/xmtp/xmtpd/pull/1169/files#diff-33dbabd792c0a769ddc7e0fb09eb3d8eddfd04a094ba2f2aa1bd5d06b6d71579), [payer_api_grpc.pb.go](https://github.com/xmtp/xmtpd/pull/1169/files#diff-a0c2abeee8804aba7fbf1caac6507ec8589a0193f39c6d912500af93bf8bf0e8), …
=> Add GetNodes gateway endpoint

cmd/xmtpd-cli/commands/funds.go, pkg/blockchain/funds_admin.go, pkg/blockchain/funds_admin_test.go, pkg/currency/currency.go, pkg/currency/currency_test.go, pkg/currency/exports_test.go, pkg/indexer/settlement_chain/contracts/payer_registry_storer.go
This change completes the withdrawal flow in the CLI and blockchain layer by wiring app-chain initiation and settlement-chain receipt, updating command UX, and consolidating balance queries to the default signer.
- Add `blockchain.fundsAdmin.Withdraw(ctx, amount)` to initiate withdrawals via `acg.AppChainGateway.Withdraw` and `blockchain.fundsAdmin.ReceiveWithdrawal(ctx)` to finalize on the settlement chain, with constructor `blockchain.NewFundsAdmin` initializing the app-chain gateway ([funds_admin.go](https://github.com/xmtp/xmtpd/pull/1170/files#diff-099ef4ce6c7e757072b1d8a5c41edc86c29b0141023a0cebe76a14c0f9d868aa)).
- Replace the CLI withdraw options to accept only `--amount`, implement `commands.withdrawHandler`, and introduce `commands.receiveWithdrawalCmd` with …
=> Finish withdrawal flow for CLI

cmd/replication/main.go
This might need a better process lifecycle manager, but this is good enough now.
=> Start the rate fetcher

cmd/xmtpd-cli/commands/admin_setup.go, cmd/xmtpd-cli/commands/appchain.go, cmd/xmtpd-cli/commands/params.go, cmd/xmtpd-cli/commands/params_appchain.go, cmd/xmtpd-cli/commands/params_bridge.go, cmd/xmtpd-cli/commands/params_settlement.go, cmd/xmtpd-cli/commands/root.go, cmd/xmtpd-cli/commands/settlement.go, pkg/blockchain/app_chain_admin.go, pkg/blockchain/app_chain_admin_test.go, pkg/blockchain/migrator/migrator_test.go, pkg/blockchain/node_registry_admin.go, pkg/blockchain/node_registry_admin_test.go, pkg/blockchain/parameter_registry_admin.go, pkg/blockchain/parameter_registry_admin_test.go, pkg/blockchain/rate_registry_admin.go, pkg/blockchain/rate_registry_admin_test.go, pkg/blockchain/registry_adapters.go, pkg/blockchain/settlement_chain_admin.go, pkg/blockchain/settlement_chain_admin_test.go, pkg/config/blockchain.go, pkg/config/options.go, pkg/config/validation.go, pkg/payerreport/workers/integration_test.go, pkg/testutils/config.go
This change replaces setter-style admin methods with `Update*` operations that read pending values from parameter registries, introduces registry adapters and interfaces to support both AppChain and Settlement registries, and updates the CLI to manage parameters directly and trigger updates separately. It also adds raw parameter get/set and a bridge command for sending parameters from Settlement to App.
- Refactor blockchain admins to use `IParameterAdmin` and `IParameterRegistry`, rename `Set*` to `Update*` without explicit values, and read state directly from contracts; adjust payload size getters to return `uint32` in [app_chain_admin.go](https://github.com/xmtp/xmtpd/pull/1182/files#diff-98ceba6374f942ed4a27f38c4bc6d9174d451fb9b7f5d83944d30a6ed4417d14) and …
=> Implement AppChain CLI management and split param setting from update

pkg/server/server_test.go, pkg/testutils/server/server.go
This change adds a `Reports` flag to `server.EnabledServices` and wires `PayerReport` configuration into test server construction, enabling the Reports service in tests with a fixed 10s attestation worker polling interval.
- Add `Reports` boolean to `server.EnabledServices` and use it to set `config.PayerReportOptions.Enable` with `AttestationWorkerPollInterval` set to 10s in `server.NewTestReplicationServer` in [server.go](https://github.com/xmtp/xmtpd/pull/1178/files#diff-a1f50c3bc62428254bc65c36229e5bb91d1ff95fe483673bf6daed86d34ee221)
- Update `TestCreateServer` to enable the Reports service for both test replication servers in [server_test.go](https://github.com/xmtp/xmtpd/pull/1178/files#diff-fe7a244e18e92d8f347af17363209172e1d79224f086b0585a1bbeef3b626c4e)
Start with …
=> Add reports test scaffolding

pkg/db/queries/identity_updates.sql.go, pkg/db/sqlc/identity_updates.sql, pkg/indexer/app_chain/contracts/identity_update_storer.go
- Add a new SQLC query `AdvisoryLockSequence` in [identity_updates.sql](https://github.com/xmtp/xmtpd/pull/1184/files#diff-4558d09ba3a749c92df38c9087258f190502cb9e749a36f261966df4c6da528e) that invokes `pg_advisory_xact_lock` using a composite key of `node_id` and `sequence_id`.
- Generate code in [identity_updates.sql.go](https://github.com/xmtp/xmtpd/pull/1184/files#diff-ad4993331be4939e7084547fb42cd62f33ffe4e5e5950c2af84733948da92b24) including `queries.advisoryLockSequence` SQL, `queries.AdvisoryLockSequenceParams` with `NodeID` and `SequenceID`, and `queries.Queries.AdvisoryLockSequence` method to execute the lock.
- Update `IdentityUpdateStorer.StoreLog` in [identity_update_storer.go](https://github.com/xmtp/xmtpd/pull/1184/files#diff-719fcd3f6b2a547b6c6f299d70464725ddf9c1161c104099b …
=> Fix Identity update StoreLog under HA

pkg/payerreport/report.go, pkg/payerreport/report_test.go, pkg/utils/hash.go
Introduce ordered hashing for node IDs and update call sites to use the new utility.
- Add `utils.PackSortAndHashNodeIDs` to sort node IDs before packing and hashing in [hash.go](https://github.com/xmtp/xmtpd/pull/1202/files#diff-7ffd86f59f106bf42eeed272b78afd1d070f392bd375f058aae45d35ee079609)
- Switch `payerreport.BuildPayerReportID` to `utils.PackSortAndHashNodeIDs` in [report.go](https://github.com/xmtp/xmtpd/pull/1202/files#diff-dd0050a86ebf68aab034bddc5e7546e74fa048e3545b5b5cafa7b78f2814e124)
- Update `payerreport.TestGetDigest` to use `utils.PackSortAndHashNodeIDs` in [report_test.go](https://github.com/xmtp/xmtpd/pull/1202/files#diff-759d8a8446dd6b48ea9222ba4877142da7fca28760bec3245f4245f441e267fe)
Start with the `utils.PackSortAndHashNodeIDs` implementation in …
=> Sort nodeIDs before packing

pkg/payerreport/generator.go, pkg/payerreport/generator_test.go, pkg/payerreport/merkle.go, pkg/payerreport/merkle_test.go, pkg/payerreport/report_test.go, pkg/payerreport/store_test.go, pkg/payerreport/testbindings_test.go, pkg/payerreport/verifier.go, pkg/payerreport/verifier_test.go
Update report verification to handle first reports without a start envelope and expose types required by tests.
- Modify `payerreport.PayerReportVerifier.getStartAndEndMessages` to return a nil start envelope when `startSequenceID == 0`, avoiding a lookup and error in [verifier.go](https://github.com/xmtp/xmtpd/pull/1206/files#diff-d3beb4e8aa9d915dbc817b4636d94a2db669a320bcfa34aa705739352d64b4e8)
- Adjust `payerreport.PayerReportVerifier.verifyMerkleRoot` to set `startMinute = 0` when the start envelope is nil in [verifier.go](https://github.com/xmtp/xmtpd/pull/1206/files#diff-d3beb4e8aa9d915dbc817b4636d94a2db669a320bcfa34aa705739352d64b4e8)
- Export `payerreport.PayerMap` and update call sites in [generator.go](https://github.com/xmtp/xmtpd/pull/1206/files#diff-e3acc56c9fb8afec4da54172140 …
=> Fix ErrMessageAtStartSequenceIDNotFound during report generation

pkg/blockchain/app_chain_admin.go, pkg/blockchain/app_chain_admin_test.go, pkg/blockchain/client.go, pkg/blockchain/errors.go, pkg/blockchain/node_registry_admin.go, pkg/blockchain/node_registry_admin_test.go, pkg/blockchain/settlement_chain_admin_test.go
- Add sentinel errors `ErrTxFailed`, `ErrTxFailedNoError`, `ErrTxNotFound`, and `ErrTxGenesisNotTraceable` in [client.go](https://github.com/xmtp/xmtpd/pull/1211/files#diff-10bd63d42f0476b000d46c9ab0629a13fcd0d38283206ae0202a52992073d990)
- Modify `pkg/blockchain/client.ExecuteTransaction` to remove gas estimation and NoSend flow, set `GasLimit` to 5,000,000, extend wait timeout to 20s, and on mined failure trace via `debug_traceTransaction` to return revert output as a `BlockchainError` in [client.go](https://github.com/xmtp/xmtpd/pull/1211/files#diff-10bd63d42f0476b000d46c9ab0629a13fcd0d38283206ae0202a52992073d990)
- Update `pkg/blockchain/client.WaitForTransaction` to return `ErrTxFailed` on failed receipts, treat `ethereum.NotFound` as a wait condition, and adjust polling behavior in …
=> Trace failed transactions
